version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  mop_music:
    build:
      context: ./mopidy
    privileged: true
    tty: true
    restart: always
    ports:
      - '6681:6680'
      - '6601:6600'
    volumes:
      - 'resin-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6633
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'  
  mop_scs:
    build:
      context: ./mopidy
    privileged: true
    tty: true
    restart: always
    ports:
      - '6682:6680'
      - '6602:6600'
    volumes:
      - 'resin-data:/data'
    depends_on:
      - 'snapserver'
    environment:
      - SNAPSERVER_PORT=6634
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
  snapserver:
    build:
      context: ./snapserver
    privileged: true
    tty: true
    restart: always
    ports:
      - '1704:1704'
      - '1705:1705'
      - '1706:1706'
      - '1780:1780'
    volumes:
      - 'resin-data:/data'
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'

